name: test and publish

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
      
  test:
    needs: build 
    
    runs-on: ubuntu-latest
    
    steps:  
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Run Unit Tests
      run: dotnet test --verbosity normal
      
  publish:
    needs: [build, test]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build with dotnet
        run: dotnet build --configuration Release --version-suffix prerelease-$(date +%Y%m%d%H%M%S)
        shell: bash
      - name: Publish nuget
        run: |
             for f in ./TextInteractor/bin/Release/*.nupkg
             do
               dotnet nuget push @$f -k secrets.NGPackagesToken -s https://api.nuget.org/v3/index.json
             done
        shell: bash
